broker_url: redis://
backend_url: redis://
my: bbb
queues:
  - celery
log:
  path: ./logs
  file: celery
  level: info
task_queues:
  - name: add
    exchange:
      name: add
      type: direct
    routing_key: add